image: docker:stable


services:
  - docker:dind


variables:
  # CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  # DOCKER_HOST: tcp://docker:2375
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2


before_script:
  - test -z "$DOCKERIMAGE" && echo "DOCKERIMAGE must be defined" && exit 1
  - test -z "$DOCKERTAG" && echo "DOCKERTAG must also be defined" && exit 1
  - docker login -u $Docker_Hub_User_Parity -p $Docker_Hub_Pass_Parity
  - docker info


.build: &docker_build
  stage: build
  script:
    - cd $DOCKERFILE_DIR
    # - docker pull $CONTAINER_IMAGE:$CONTAINER_TAG || true
    # - docker build --cache-from $CONTAINER_IMAGE:$CONTAINER_TAG --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:$CONTAINER_TAG .
    - CONTAINER_DATE_TAG="$CONTAINER_TAG-$(date +%Y%m%d)"
    - docker build --tag $CONTAINER_IMAGE:$CONTAINER_DATE_TAG --tag $CONTAINER_IMAGE:$CONTAINER_TAG .
    - docker push $CONTAINER_IMAGE:$CONTAINER_DATE_TAG
    - docker push $CONTAINER_IMAGE:$CONTAINER_TAG
  only:
    refs:
      - schedules
      - web
    kubernetes: active
  tags:
    - kubernetes



build:rust:nightly:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE: parity/rust
    CONTAINER_TAG:   nightly
    DOCKERFILE_DIR:  docker-files-for-Gitlab-CI-rust/rustup
  only:
    variables:
      - $DOCKERIMAGE == "parity/rust"
      - $DOCKERTAG   == "nightly"


build:rust-android:gitlab-ci:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE: parity/rust-android
    CONTAINER_TAG:   gitlab-ci
    DOCKERFILE_DIR:  docker-files-for-Gitlab-CI-rust/cross/android
  only:
    variables:
      - $DOCKERIMAGE == "parity/rust-android"
      - $DOCKERTAG   == "gitlab-ci"

# disable nightly builds here as they are images build now directly from the 
# ci of substrate and can be scheduled there if really needed.
# build:substrate:nightly:
#   <<: *docker_build
#   variables:
#     CONTAINER_IMAGE: parity/substrate
#     CONTAINER_TAG:   nightly
#     DOCKERFILE_DIR:  docker-files-for-Gitlab-CI-rust/substrate
#   only:
#     variables:
#       - $DOCKERIMAGE == "parity/substrate"
#       - $DOCKERTAG   == "nightly"

build:awscli:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE: parity/awscli
    CONTAINER_TAG:   latest
    DOCKERFILE_DIR:  awscli
  only:
    variables:
      - $DOCKERIMAGE == "parity/awscli"
      - $DOCKERTAG   == "latest"


# vim: expandtab sts=2
